/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>
#include <main.h>
#include <clockconfig.h>
#include <gpio.h>
#include <timer.h>
#include <interrupt.h>
#include <encoder.h>
#include <motor.h>
#include <spi.h>
#include <display.h>

int8_t gDrawFlag = 0;

//#if !defined(__SOFT_FP__) && defined(__ARM_FP)
//  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
//#endif

int main(void)
{
    sysClockConfig();
    gpioInit();
    interruptInit();
    TIM3Init();
    TIM4Init();
    TIM8Init();
    TIM15Init();
    SPI3Init();
    SysTick_Config(SystemCoreClock / 1000);
    attemptSetMotorDirection(MOTOR_FORWARD);
    setMotorDuty(0);
    displayInit();
    printf("Initialization done.\n");



    while(1){
        if (gDrawFlag == 1){
            gDrawFlag = 0;
            drawDisplay();
        }
    }
}






//function to allow printing to console
int _write(int file, char *ptr, int len)
{
    int i=0;
    for(i=0 ; i<len ; i++)
        ITM_SendChar((*ptr++));
    return len;
}


